//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshevoi_Jurnal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jurnal
    {
        public int id { get; set; }
        public Nullable<int> id_studenta { get; set; }
        public Nullable<int> id_disciplini { get; set; }
        public Nullable<int> id_ocenki { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Ocenki Ocenki { get; set; }
        public virtual Student Student { get; set; }
    }
}
